version: 1.10.1
name: MG
main: me.nao.main.game.Main
api-version: 1.17
author: NAO2706
description: Minigame
softdepend: [NBTAPI]


commands: 
     mg:
        description: Comando de op
        aliases:
        - minigame
        - nao-game
 